import ollama
import pandas as pd

prompt = ("This is an excerpt from a discussion between tutors and students in a zoom classroom. The transcript was automatically "
          "generated by a speech recognition system. This system introduced errors into the transcription. This "
          "error significantly impacts downstream tasks, reducing accuracy and increasing bias. It is critical to KEEP "
          "mistakes that weere originally made by the student or tutor, but CORRECT errors created by the speech recognition system."
          "Here are 7 lines from the transcript. Look at the middle utterance and 1) print the utterance, 2) indicate if the utterance"
          "has one or more errors, 3) indicate if the errors are likely introduced by the speech recognition system, and 4) if there "
          "are introduced errors, what is the corrected sentence. Several lines of context are provided to help decide if"
          "the utterance was transcribed accurately, do not analyse errors in those lines. \n\n")



file = "0c4fb37f-af97-febf-3a8b-0b802190e35c.xlsx"
transcript = pd.read_excel(file)
transcript = transcript.dropna(how="any")
length_transcript = len(transcript)
print(length_transcript)
transcript["deepseek_response"] = ""
print(transcript.columns)

for i in range(3, length_transcript-3):
    line = " \n <middle>" + transcript.iloc[i,3] + ": " + transcript.iloc[i,5] + " </middle>\n"
    pre_context = (("<context> " + transcript.iloc[i-3,3] + ": " + transcript.iloc[i-3,5] + "\n" +
                   transcript.iloc[i-2,3] + ": " + transcript.iloc[i-2,5]) + "\n" +
                   transcript.iloc[i-1,3] + ": " + transcript.iloc[i-1,5] + " </context>")

    post_context = (("<context> " + transcript.iloc[i+1,3] + ": " + transcript.iloc[i+1,5] + "\n" +
                   transcript.iloc[i+2,3] + ": " + transcript.iloc[i+2,5]) + "\n" +
                   transcript.iloc[i+3,3] + ": " + transcript.iloc[i+3,5] + " </context>")

    prompt_line = prompt + pre_context + line + post_context
    print(prompt_line)

    response = ollama.chat(
        model='deepseek-r1:1.5b',
        messages=[
            {'role': 'user', 'content': prompt_line}
        ]
    )

    transcript.iloc[i,11] = response['message']['content']

    # Print the response
    # with open("test.txt", 'w') as file:
    #     file.write(response['message']['content'])

    print(response['message']['content'])

transcript.to_excel("test_file.xlsx")